name = "liantang-fun"
compatibility_date = "2026-04-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "liantang-fun"
database_id = "1cb9eb84-e719-4d5a-8495-d24f0f6c4f56"

[vars]
APP_URL = "https://liantang.fun"
